### ISSUE TITLE
OTD crashes on startup with newest WindowsInk version

### ISSUE THREAD

**Issue by ienooo** [X9VoiD/VoiDPlugins#32]
I installed the new version of WindowsInk but uppon starting OTD it always crashes. First time using WindowsInk again absolute mode worked perfectly fine but with relative mode it doesnt register my pen tip clicking. Closing and opening crashes OTD, as staded above.

OpenTabletDriver.Daemon.exe gives following error:

```
[Detect:Warning]        Another tablet driver found: Wacom
[Detect:Error]  Detected input coming from Wacom driver
[Plugin:Debug]  Loading plugin 'WindowsInk'
[Detect:Info]   Searching for tablets...
[Detect:Debug]  Searching for tablet '10moon 1060N'
[Detect:Debug]  Searching for tablet 'Acepen AP 1060'
[Detect:Debug]  Searching for tablet 'Artisul M0610 Pro'
[Detect:Debug]  Searching for tablet 'Gaomon 1060 Pro'
[Detect:Debug]  Searching for tablet 'Gaomon M106K Pro'
[Detect:Debug]  Searching for tablet 'Gaomon M106K'
[Detect:Debug]  Searching for tablet 'Gaomon M10K Pro'
[Detect:Debug]  Searching for tablet 'Gaomon M10K'
[Detect:Debug]  Searching for tablet 'Gaomon M1220'
[Detect:Debug]  Searching for tablet 'Gaomon M1230'
[Detect:Debug]  Searching for tablet 'Gaomon PD1161'
[Detect:Debug]  Searching for tablet 'Gaomon PD1560'
[Detect:Debug]  Searching for tablet 'Gaomon S56K'
[Detect:Debug]  Searching for tablet 'Gaomon S620'
[Detect:Debug]  Searching for tablet 'Gaomon S630'
[Detect:Debug]  Searching for tablet 'Genius G-Pen 560'
[Detect:Debug]  Searching for tablet 'Genius i608x'
[Detect:Debug]  Searching for tablet 'Huion 420'
[Detect:Debug]  Searching for tablet 'Huion G10T'
[Detect:Debug]  Searching for tablet 'Huion GC610'
[Detect:Debug]  Searching for tablet 'Huion GT-220 V2'
[Detect:Debug]  Searching for tablet 'Huion GT-221 Pro'
[Detect:Debug]  Searching for tablet 'Huion H1060P'
[Detect:Debug]  Searching for tablet 'Huion H1161'
[Detect:Debug]  Searching for tablet 'Huion H420'
[Detect:Debug]  Searching for tablet 'Huion H420X'
[Detect:Debug]  Searching for tablet 'Huion H430P'
[Detect:Debug]  Searching for tablet 'Huion H610 Pro V2'
[Detect:Debug]  Searching for tablet 'Huion H610 Pro'
[Detect:Debug]  Searching for tablet 'Huion H640P'
[Detect:Debug]  Searching for tablet 'Huion H950P'
[Detect:Debug]  Searching for tablet 'Huion HC16'
[Detect:Debug]  Searching for tablet 'Huion HS610'
[Detect:Debug]  Searching for tablet 'Huion HS611'
[Detect:Debug]  Searching for tablet 'Huion HS64'
[Detect:Debug]  Searching for tablet 'Huion Kamvas 13'
[Detect:Debug]  Searching for tablet 'Huion Kamvas 16 (2021)'
[Detect:Debug]  Searching for tablet 'Huion Kamvas 16'
[Detect:Debug]  Searching for tablet 'Huion Kamvas 20'
[Detect:Debug]  Searching for tablet 'Huion Kamvas 22 Plus'
[Detect:Debug]  Searching for tablet 'Huion Kamvas Pro 12'
[Detect:Debug]  Searching for tablet 'Huion Kamvas Pro 13'
[Detect:Debug]  Searching for tablet 'Huion Kamvas Pro 16'
[Detect:Debug]  Searching for tablet 'Huion Kamvas Pro 20'
[Detect:Debug]  Searching for tablet 'Huion New 1060 Plus (2048)'
[Detect:Debug]  Searching for tablet 'Huion New 1060 Plus'
[Detect:Debug]  Searching for tablet 'Huion Q11K V2'
[Detect:Debug]  Searching for tablet 'Huion Q11K'
[Detect:Debug]  Searching for tablet 'Huion Q620M'
[Detect:Debug]  Searching for tablet 'Huion WH1409 V2'
[Detect:Debug]  Searching for tablet 'Huion WH1409'
[Detect:Debug]  Searching for tablet 'Parblo A610 Pro'
[Detect:Debug]  Searching for tablet 'Parblo A640 V2'
[Detect:Debug]  Searching for tablet 'Parblo Intangbo M'
[Detect:Debug]  Searching for tablet 'Parblo Intangbo S'
[Detect:Debug]  Searching for tablet 'Parblo Ninos M'
[Detect:Debug]  Searching for tablet 'Parblo Ninos S'
[Detect:Debug]  Searching for tablet 'UC-Logic 1060N'
[Detect:Debug]  Searching for tablet 'UC-Logic PF1209'
[Detect:Debug]  Searching for tablet 'UGTABLET M708'
[Detect:Debug]  Searching for tablet 'VEIKK A15 Pro'
[Detect:Debug]  Searching for tablet 'VEIKK A15'
[Detect:Debug]  Searching for tablet 'VEIKK A30'
[Detect:Debug]  Searching for tablet 'VEIKK A50 V2'
[Detect:Debug]  Searching for tablet 'VEIKK A50'
[Detect:Debug]  Searching for tablet 'VEIKK S640 V2'
[Detect:Debug]  Searching for tablet 'VEIKK S640'
[Detect:Debug]  Searching for tablet 'VEIKK VK640'
[Detect:Debug]  Searching for tablet 'ViewSonic Woodpad PF0730'
[Detect:Debug]  Searching for tablet 'Wacom CTE-430'
[Detect:Debug]  Searching for tablet 'Wacom CTE-440'
[Detect:Debug]  Searching for tablet 'Wacom CTE-450'
[Detect:Debug]  Searching for tablet 'Wacom CTE-460'
[Detect:Debug]  Searching for tablet 'Wacom CTE-630'
[Detect:Debug]  Searching for tablet 'Wacom CTE-640'
[Detect:Debug]  Searching for tablet 'Wacom CTE-650'
[Detect:Debug]  Searching for tablet 'Wacom CTF-430'
[Detect:Debug]  Searching for tablet 'Wacom CTH-460'
[Detect:Debug]  Searching for tablet 'Wacom CTH-461'
[Detect:Debug]  Searching for tablet 'Wacom CTH-470'
[Detect:Debug]  Searching for tablet 'Wacom CTH-480'
[Detect:Debug]  Searching for tablet 'Wacom CTH-490'
[Detect:Debug]  Searching for tablet 'Wacom CTH-661'
[Detect:Debug]  Searching for tablet 'Wacom CTH-670'
[Detect:Debug]  Searching for tablet 'Wacom CTH-680'
[Detect:Debug]  Searching for tablet 'Wacom CTH-690'
[Detect:Debug]  Searching for tablet 'Wacom CTL-4100'
[Detect:Debug]  Searching for tablet 'Wacom CTL-4100WL'
[Detect:Debug]  Searching for tablet 'Wacom CTL-460'
[Detect:Debug]  Searching for tablet 'Wacom CTL-470'
[Detect:Debug]  Searching for tablet 'Wacom CTL-471'
[Detect:Debug]  Searching for tablet 'Wacom CTL-472'
[Detect:Debug]  Searching for tablet 'Wacom CTL-480'
[Detect:Debug]  Searching for tablet 'Wacom CTL-490'
[Detect:Debug]  Searching for tablet 'Wacom CTL-6100WL'
[Detect:Debug]  Searching for tablet 'Wacom CTL-671'
[Detect:Debug]  Searching for tablet 'Wacom CTL-672'
[Detect:Debug]  Searching for tablet 'Wacom CTL-680'
[Detect:Debug]  Searching for tablet 'Wacom CTL-690'
[Detect:Debug]  Searching for tablet 'Wacom DTC-133'
[Detect:Debug]  Searching for tablet 'Wacom ET-0405-U'
[Detect:Debug]  Searching for tablet 'Wacom ET-0405A-U'
[Detect:Debug]  Searching for tablet 'Wacom FT-0405-U'
[Detect:Debug]  Searching for tablet 'Wacom GD-0405-U'
[Detect:Debug]  Searching for tablet 'Wacom GD-0608-U'
[Detect:Debug]  Searching for tablet 'Wacom GD-0912-U'
[Detect:Debug]  Searching for tablet 'Wacom GD-1212-U'
[Detect:Debug]  Searching for tablet 'Wacom GD-1218-U'
[Detect:Debug]  Searching for tablet 'Wacom MTE-450'
[Detect:Debug]  Searching for tablet 'Wacom PTH-450'
[Detect:Debug]  Searching for tablet 'Wacom PTH-451'
[Detect:Debug]  Searching for tablet 'Wacom PTH-460'
[Detect:Debug]  Searching for tablet 'Wacom PTH-650'
[Detect:Debug]  Searching for tablet 'Wacom PTH-651'
[Detect:Debug]  Searching for tablet 'Wacom PTH-660'
[Detect:Debug]  Searching for tablet 'Wacom PTH-850'
[Detect:Debug]  Searching for tablet 'Wacom PTH-851'
[Detect:Debug]  Searching for tablet 'Wacom PTH-860'
[Detect:Debug]  Searching for tablet 'Wacom PTK-1240'
[Detect:Debug]  Searching for tablet 'Wacom PTK-440'
[Detect:Debug]  Searching for tablet 'Wacom PTK-450'
[Detect:Debug]  Searching for tablet 'Wacom PTK-540WL'
[Detect:Debug]  Searching for tablet 'Wacom PTK-640'
[Detect:Debug]  Searching for tablet 'Wacom PTK-650'
[Detect:Debug]  Searching for tablet 'Wacom PTK-840'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-1230'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-1231W'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-430'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-431W'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-630'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-631W'
[Detect:Debug]  Searching for tablet 'Wacom PTZ-930'
[Detect:Debug]  Searching for tablet 'Wacom XD-0405-U'
[Detect:Debug]  Searching for tablet 'Wacom XD-0608-U'
[Detect:Debug]  Searching for tablet 'Wacom XD-0912-U'
[Detect:Debug]  Searching for tablet 'Wacom XD-1212-U'
[Detect:Debug]  Searching for tablet 'Wacom XD-1218-U'
[Detect:Debug]  Searching for tablet 'XenceLabs Pen Tablet Medium'
[Detect:Debug]  Searching for tablet 'XP-Pen Artist 12 Pro'
[Detect:Debug]  Searching for tablet 'XP-Pen Artist 12 V2'
[Detect:Debug]  Searching for tablet 'XP-Pen Artist 12'
[Detect:Debug]  Searching for tablet 'XP-Pen Artist 15.6 Pro'
[Detect:Debug]  Searching for tablet 'XP-Pen Artist 22HD'
[Detect:Debug]  Searching for tablet 'XP-Pen CT1060'
[Detect:Debug]  Searching for tablet 'XP-Pen CT430'
[Detect:Debug]  Searching for tablet 'XP-Pen CT640'
[Detect:Debug]  Searching for tablet 'XP-Pen Deco 01 V2 (variant 2)'
[Detect:Debug]  Searching for tablet 'XP-Pen Deco 01 V2'
[Detect:Debug]  Searching for tablet 'XP-Pen Deco 01'
[Detect:Debug]  Searching for tablet 'XP-Pen Deco 02'
[Detect:Debug]  Searching for tablet 'XP-Pen Deco 03'
[Detect:Debug]  Searching for tablet 'XP-Pen Deco mini4'
[Detect:Debug]  Searching for tablet 'XP-Pen Deco mini7'
[Detect:Debug]  Searching for tablet 'XP-Pen Deco Pro Medium'
[Detect:Debug]  Searching for tablet 'XP-Pen Deco Pro Small'
[Detect:Debug]  Searching for tablet 'XP-Pen Innovator 16'
[Detect:Debug]  Searching for tablet 'XP-Pen Star 03'
[Detect:Debug]  Searching for tablet 'XP-Pen Star 05 V3'
[Detect:Debug]  Searching for tablet 'XP-Pen Star 06'
[Detect:Debug]  Searching for tablet 'XP-Pen Star 06C'
[Detect:Debug]  Searching for tablet 'XP-Pen Star G430'
[Detect:Debug]  Searching for tablet 'XP-Pen Star G430S V2'
[Detect:Debug]  Searching for tablet 'XP-Pen Star G430S'
[Detect:Debug]  Searching for tablet 'XP-Pen Star G540 Pro'
[Detect:Debug]  Searching for tablet 'XP-Pen Star G540'
[Detect:Debug]  Searching for tablet 'XP-Pen Star G640 V2'
[Detect:Debug]  Searching for tablet 'XP-Pen Star G640'
[Device:Debug]  Initializing device 'STAR G640' \\?\hid#vid_28bd&pid_0094&mi_02#8&25b102a4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[Device:Debug]  Using report parser type 'OpenTabletDriver.Configurations.Parsers.XP_Pen.XP_PenReportParser'
[Device:Debug]  Set device output: 02-B0-02
[Detect:Info]   Found tablet 'XP-Pen Star G640'
[Detect:Debug]  Searching for tablet 'XP-Pen Star G640S'
[Detect:Debug]  Searching for tablet 'XP-Pen Star G960'
[Detect:Debug]  Searching for tablet 'XP-Pen Star G960S Plus'
[Detect:Debug]  Searching for tablet 'XP-Pen Star G960S'
[XP-Pen Star G640:Info] Output mode: Relative Mode
[XP-Pen Star G640:Info] Relative Mode Sensitivity (X, Y): <10, 10>
[XP-Pen Star G640:Info] Relative Mode Rotation: 0
[XP-Pen Star G640:Info] Reset time: 00:00:00.1000000
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'XP-Pen Star G640' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at VoiDPlugins.Library.VoiD.GlobalStore`1.Get(TabletReference tabletReference) in /home/runner/work/VoiDPlugins/VoiDPlugins/src/VoiDPlugins.Library/VoiD/GlobalStore.cs:line 45
   at VoiDPlugins.OutputMode.WindowsInkButtonHandler.Initialize(TabletReference tabletReference) in /home/runner/work/VoiDPlugins/VoiDPlugins/src/OutputMode/WindowsInk/WinInkButtonHandler.cs:line 34
   at VoiDPlugins.OutputMode.WindowsInkButtonHandler.set_Reference(TabletReference value) in /home/runner/work/VoiDPlugins/VoiDPlugins/src/OutputMode/WindowsInk/WinInkButtonHandler.cs:line 30
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.InvokeOneParameter(Object obj, BindingFlags invokeAttr, Binder binder, Object parameter, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at OpenTabletDriver.Desktop.Reflection.PluginSettingStore.TriggerEventMethods(Object obj, TabletReference tabletReference)
   at OpenTabletDriver.Desktop.Reflection.PluginSettingStore.Construct[T](IServiceManager provider, TabletReference tabletReference)
   at OpenTabletDriver.Daemon.DriverDaemon.SetBindingHandlerSettings(InputDeviceTree dev, IOutputMode outputMode, BindingSettings settings, TabletReference tabletReference)
   at OpenTabletDriver.Daemon.DriverDaemon.SetSettings(Settings settings)
   at OpenTabletDriver.Daemon.DriverDaemon.LoadUserSettings()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by ienooo** [comment]
Tried reinstalling the driver again: 
Now, when using WindowsInk in relative mode, im only able to use a fraction of my monitor since the coursor wont move out of that corner. When using my tablet, it will return into said corner when it has previously been moved outside with e.g. my mouse. 
Registers pen clicks, not sure about pen pressure.
OTD does not crash after a program restart but it behaves as stated before.

**Comment by X9VoiD** [comment]
Resolved by 10b4b008232f1bfea3711473f882864c13ede151
